# Generated by Django 4.2.27 on 2025-12-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earthquake_id', models.CharField(max_length=256)),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('depth', models.FloatField(default=0)),
            ],
        ),
    ]
