# Generated by Django 4.2.27 on 2025-12-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake',
            name='magnitude',
            field=models.FloatField(default=0),
        ),
    ]
