# Generated by Django 4.2.27 on 2025-12-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0002_earthquake_magnitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
