# Generated by Django 4.2.27 on 2025-12-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0003_earthquake_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake',
            name='place',
            field=models.CharField(default='', max_length=256),
        ),
    ]
